spring.application.name=student-management

# 1. Cấu hình kết nối PostgreSQL (Thay 'postgres' và 'mat_khau_cua_ban' cho đúng với máy bạn)
spring.datasource.url=jdbc:postgresql://localhost:5432/student_management
spring.datasource.username=postgres
spring.datasource.password=phu
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Cấu hình JPA / Hibernate (Tự động tạo bảng)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true