spring.application.name=student-management

# === GÁN CỨNG CẤU HÌNH CỦA NEON.TECH ĐỂ TEST ===
# Thêm tiền tố "jdbc:" vào đầu chuỗi kết nối của Neon
spring.datasource.url=jdbc:postgresql://ep-super-wind-a12e4fu6-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
# Bóc tách username và password từ chuỗi kết nối
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ovT7Vt9lnmAJ
# ===============================================

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true