spring.application.name=student-management

# Cấu hình để đọc từ biến môi trường, NẾU KHÔNG CÓ thì dùng giá trị mặc định cho máy local
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/student_management}
spring.datasource.username=${DB_USERNAME:tdung}
spring.datasource.password=${DB_PASSWORD:buddha}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true